### ISSUE TITLE
AI Doesn't Listen To Commands 

### ISSUE THREAD

**Issue by cpl-Jacktomm** [zen-mod/GME_AR#40]
**Arma Reforger Version:** `1.x.x.x` (stable / experimental)
**GME Version:** `1.2.1`

**Mods:**
```
- GME
```

**Description:**
Add a detailed description of the error. This makes it easier for us to fix the issue.

**Expected behavior:**

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Workbench

**Additional information:**
Provide any additional information that will help us solve this issue.

**console.log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server `console.log` file. An instruction to find your log files can be found [here](https://community.bistudio.com/wiki/Arma_Reforger:Crash_Report).

**Screenshots:**

**Comment by Kexanone** [comment]
Can you please fill put the template properly?

**Comment by Kexanone** [comment]
Also keep in mind that if it's a vanilla GM issue, you should report it in the official Reforger feedback tracker instead.

**Comment by cpl-Jacktomm** [comment]
all good the issue was a civilian faction
